# Generated by Django 4.2.1 on 2023-07-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_course_image_course_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
    ]
