# Generated by Django 4.2.1 on 2023-07-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_favoritecourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecourses',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
