# Generated by Django 4.2.1 on 2023-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studentassignment_student_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='student-profile-imgs/'),
        ),
    ]
