# Generated by Django 4.2.1 on 2023-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_for', models.CharField(max_length=50)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notif_read_status', models.BooleanField(default=False)),
            ],
        ),
    ]
